---

- name: Download the StatsD release tarball
  get_url:
    url: "{{statsd_package_url}}"
    dest: "/tmp/{{statsd_package}}.tar.gz"
  register: statsd_release
  tags:
    - deps
    - statsd
    - monitoring

- name: Extract StatsD from the tarball
  when: statsd_release|changed
  unarchive:
    copy: no
    src: "/tmp/{{statsd_package}}.tar.gz"
    dest: "/tmp"
    creates: "/tmp/{{statsd_package}}/package.json"
  tags:
    - deps
    - statsd
    - monitoring

- name: Install StatsD
  when: statsd_release|changed
  sudo: yes
  command: "rsync -av --delete '/tmp/{{statsd_package}}/' '{{statsd_install_dir}}'"
  tags:
    - deps
    - statsd
    - monitoring

- name: "Update NPM dependencies"
  sudo: yes
  npm:
    path: "{{statsd_install_dir}}"
    state: latest
    production: yes
  tags:
    - deps
    - statsd
    - monitoring

- name: "Install extra packages"
  sudo: yes
  npm:
    name: "{{item}}"
    path: "{{statsd_install_dir}}"
    latest: yes
    production: yes
  with_items: statsd_extra_packages
  tags:
    - deps
    - statsd
    - monitoring
